eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
  #开发环境关闭自我保护机制 生产环境删除此配置
  server:
    enable-self-preservation: false
#  instance:
#    hostname: peer1
spring:
  application:
    name: eureka
server:
  port: 8761